### ISSUE TITLE
Add Float Point

### ISSUE THREAD

**Issue by artasparks** [otrego/clamshell#131]
Right now the point provided in `core/point` is an integer point. But, we're also going to need a float64 point for representing points in space (like when creating diagrams or making UIs).

So, we should make a new Point struct. Maybe `Coord` (coordinate) as a name? 

```
type Coord struct {
  x float64
  y float64
}
```

etc.

**Comment by artasparks** [comment]
Note: there's some prior art in https://github.com/Kashomon/bodoko if you're curious.

**Comment by jonathanmli** [comment]
What else do we need to integrate besides adding a new coord struct in `core/point`?

**Comment by artasparks** [comment]
That's it for now. There's a bunch of other stuff we can start thinking about after =)
