### ISSUE TITLE
Add unit test for move.FromSGFPoint

### ISSUE THREAD

**Issue by artasparks** [otrego/clamshell#175]
We should have a unit test for `move.FromSGFPoint`; Currently there aren't any unit tests. 

Background:

* For more about unit testing and Golang, see: https://golang.org/pkg/testing/
* We also have some basic tests at [movetree_test.go](https://github.com/otrego/clamshell/blob/master/core/movetree/movetree_test.go) and [point_test.go](https://github.com/otrego/clamshell/blob/master/core/point/point_test.go)

Requirements:

- Should have a basic unit test that tests the happy-path
- Should have test both the happy-path and error-conditions.

**Comment by Brandf3** [comment]
Fixed with #191
