### ISSUE TITLE
Move GameInfo from a node-property to a game-property

### ISSUE THREAD

**Issue by artasparks** [otrego/clamshell#193]
We should move the `GameInfo` property from a node-level property to a MoveTree level property.

As of writing, GameInfo exists on the node-struct: 

```go
type Node struct {
...
	GameInfo *GameInfo
...
}
```

Given that only the root node can have game info, we should move that to live just on the Movetree:

```go
// MoveTree contains the game tree information for a go game.
type MoveTree struct {
	Root *Node
	GameInfo *GameInfo
}
```

Requirements: just a move is fine. I don't think we should need new unit tests.

**Comment by RodDeacon** [comment]
Started working on this issue last night. Ran into some dependency issues I'm not sure how to fix. Hopefully we can discuss at the next hack.

**Comment by artasparks** [comment]
Oh gosh, I started to work on this issue too. At this point I think that

1. I'm not sure it's a good idea.
2. It's quite a bit of work -- enough that it's probably SDK. 

Personally, I'd recommend another DDK issue. I was thinking about just closing this one.
