### ISSUE TITLE
Improvements for Parser

### ISSUE THREAD

**Issue by artasparks** [otrego/clamshell#21]
It would be nice to improve the parser/scanner to be more robust / give better error signals. In particular, we should have:

* Better testing
* Handling of edge cases
* Custom type for control chars
* Scan() needs to return number of characters scanned

**Comment by jared-nishikawa** [comment]
The custom type and adjustments to scan() were straightforward.  I just made a PR with another iteration of testing and edge cases.  Not necessarily complete, but at least a tidier framework for testing.  Interested in your thoughts regarding the structure

**Comment by artasparks** [comment]
Done with #85
