### ISSUE TITLE
issue with cmake katago gpu install

### ISSUE THREAD

**Issue by RodDeacon** [otrego/clamshell#30]
I am struggling with a portion of the installation of katago on windows. If anyone has experience with Cmake I would appreciate a little help later this evening from around 7 ~ 8 whenever you are available just ping me on discord. 

Thanks,

-Rodney

**Comment by artasparks** [comment]
@RodDeacon -- did you figure this out? I'm going to close since it's not an issue with the repo per se. 

I would try just running katago-for-windows binaries with lizzie or another program and see if it works: https://github.com/lightvector/KataGo/releases
