### ISSUE TITLE
Serve Basic Web Content

### ISSUE THREAD

**Issue by artasparks** [otrego/clamshell#45]
We should have some way for serving web content. It's not clear what precisely this should look like. It could just be built into the server directly as static content with go-bindata.

Or it could served with one of the file-serving go plugins. Or, it could even be served from some static content system. Or possibly S3/CloudFornt.

**Comment by mhoak** [comment]
Plan is to set up terraform to configure a GCP bucket for static serving initially. Depends on https://github.com/otrego/clamshell/issues/48.

**Comment by artasparks** [comment]
https://medium.com/@hau12a1/golang-http-serve-static-files-correctly-5feb98ae9da1

**Comment by dbarnett** [comment]
What would be a good first bit of static content to serve?

**Comment by artasparks** [comment]
Oh, just in `index.html` page and some basic css. Just something to get us off the ground.

**Comment by artasparks** [comment]
This should be MUCH easier now with go-embed https://golang.org/pkg/embed/

**Comment by artasparks** [comment]
This is now done.
