### ISSUE TITLE
Add automation for Go-code quality

### ISSUE THREAD

**Issue by artasparks** [otrego/clamshell#6]
We should add automation to ensure we automatically check.

- gofmt
- govet
- golint
- tests pass

**Comment by artasparks** [comment]
https://github.com/marketplace?type=actions Might be a good choice. Or we can use CircleCI or Travis

**Comment by mhoak** [comment]
This is going to be broken into two pieces. 
1) Adding github actions for CI (https://github.com/otrego/clamshell/pull/18)
2) Adding some git commit hooks and the documentation for them.
