### ISSUE TITLE
Convert treepath into string

### ISSUE THREAD

**Issue by artasparks** [otrego/clamshell#97]
We have methods that convert treepaths ("0.2.0.3.0:5") to internal data structures. Now we need a method to convert the treepath to a string. 

Ex 

```
tp, err := treepath.Parse("0.0.0.0")
...
tp.String() => "[0, 0, 0, 0]"
tp.Serialize() => "0:4"
```

Or maybe we want to have String returned the shortened form? Not totally sure.

For reference: https://github.com/otrego/clamshell/tree/master/core/treepath

**Comment by KiloLimaFoxtrot** [comment]
I am interested in this task because it deals with data structure concepts. If this task is not claimed it by the time I finish my already assigned tasks, I will self-assign this task.

**Comment by artasparks** [comment]
Go for it =)
